### ISSUE TITLE
Impossible to disable this inventory mod.

### ISSUE THREAD

**Issue by Lazerbeak12345** [mt-historical/i3#17]
**Describe the bug**
It's an expectation that inventory mods can be disabled by other mods. There is no way to do this with this mod.

**To Reproduce**
Steps to reproduce the behavior.

There is no dedicated flag (like `sfinv.enabled`) to i3. (thus it fails)

If I try this:

```lua
if minetest.global_exists("i3") then
    function i3.set_fs() end
end
```

It also doesn't work, since most/all references to `set_fs` in this mod aren't absolute references.

**Ideas for solutions**

1. Add `i3.enabled` defaulting to true. At the top of `i3.set_fs` if that variable is false, return and do nothing.
2. Alternatively, in every place where `i3.set_fs` is used, reference it absolutely, instead of a dereferenced local variable at the top of the file.

**Screenshots**

**Additional context**
- Mod version? Release or git? (any, any)
- Engine version? (any any)
- LuaJIT enabled? (any)
- Operating system? (any)
- Did you try to disable other mods except i3? (yes, works standalone on mtg)

**Comment by wsor4035** [comment]
nah, users can disable/remove the mod if they dont want it (plus i dont think unified inventory does this either)

**Comment by Lazerbeak12345** [comment]
I'm 100% okay with this outcome - though I should note that unified inventory _is_ possible to disable. (in fact, i3 does just that).

Thanks for your time.

**Comment by wsor4035** [comment]
it sets `function unified_inventory.set_inventory_formspec() return end` (not an actual variable anywhere) which could end up in weirdness if unified inventory is listening to fields coming back and does something 🤔 

why do you even want to disable it via a mod?

**Comment by Lazerbeak12345** [comment]
Well, it is an actual variable, defined here.

https://github.com/minetest-mods/unified_inventory/blob/16265dca2dc2133fb9dd8bf31efd78077fa91a3d/internal.lua#L332

The reason I would want to disable it via a mod is that it is the norm for inventory mods to disable other inventory mods if they are present, and I am developing/have-developed an inventory mod to compete with i3.

However - I honesty don't like this de-facto way of doing things, and would rather that _should_ multiple inventory mods be installed, individual players must be able to choose between them, or they should assert an error, per your recommendation.

Since making that choice possible is... near impossible without _another_ mod, .... yeah asserting is what I'd _like_ but goes against the norm.

**Comment by wsor4035** [comment]
thats a function, not a variable

**Comment by Lazerbeak12345** [comment]
I'm honestly confused why you would think that. Lua functions are stored in variables. UI allows that function to be overridden. I tested it yesterday and that I3 code works.


I'll still reiterate though, I'm still fine with this outcome.

**Comment by AmyGilhespy** [comment]
I would also like to be able to disable i3.  I wanted to write a mod that lets players choose which inventory they want to use, but it's extremely difficult with i3.

**Comment by Lazerbeak12345** [comment]
> I wanted to write a mod that lets players choose which inventory they want to use

For the record, I'd accept a
PR for changes enabling that feature in my competing inventory, sway. Sway's current implementation would prevent such a mod from working. I've wanted to make such a mod myself (but haven't had time), and would love to see what you create.

Its also one reason a proper enablement mechanism should be a part of every "modern" inventory mod.
