### ISSUE TITLE
3d armor shields in i3 crash lock minetest once world is restarted

### ISSUE THREAD

**Issue by wsor4035** [mt-historical/i3#7]
**Describe the bug**
reported on behalf of another user
minetest is crash locked by i3+3d_armor+restart

**To Reproduce**
* turn on progressive mode
* give yourself `shields:shield_wood`
* put in armor slot in i3
* restart world
* get locked out due to crash

**Screenshots**

**Additional context**
3d armor issue: https://github.com/minetest-mods/3d_armor/issues/135

**Comment by wsor4035** [comment]
here is a patch to at least get back into your world. this might just mask the actual issue tho, havent dug into it

```git
diff --git a/src/gui.lua b/src/gui.lua
index 7f654f2..1f83748 100644
--- a/src/gui.lua
+++ b/src/gui.lua
@@ -1576,7 +1576,7 @@ local function get_items_fs(fs, data, player, full_height)
 			local item_btn = fmt("item_image_button", X, Y, size, size, name, item, "")
 
 			if recipe_filter_set() and data.itab == 1 then
-				if data.items_progress[item] then
+				if data.items_progress and data.items_progress[item] then
 					insert(fs, item_btn)
 				else
 					local col = "^\\[colorize:#232428^\\[opacity:245"

```

**Comment by TristanCottam** [comment]
I encountered this error on a previously working world of mine which already had `i3_progressive_mode` enabled before the bug.
